# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca607a8adfb5af01ebfa91edc69f51ef"
name = "Storefront Randomizer"
application_url = "https://storefront-randomizer-395930598833.us-west3.run.app"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://storefront-randomizer-395930598833.us-west3.run.app/auth/callback",
  "https://storefront-randomizer-395930598833.us-west3.run.app/auth/shopify/callback"
]
