# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca607a8adfb5af01ebfa91edc69f51ef"
name = "Storefront Randomizer"
application_url = "https://storefront-randomizer-395930598833.us-west3.run.app"
embedded = false

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "write_products,read_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://storefront-randomizer-395930598833.us-west3.run.app/auth/callback",
  "https://storefront-randomizer-395930598833.us-west3.run.app/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
